export const masteryData = [
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/profile-picture.jpg',
  },
];
