export const masteryData = [
  {
    id: 1,
    name: 'HTML',
    percentage: '100%',
    image: '/images/logos/html-logo.png',
  },
  {
    id: 2,
    name: 'CSS',
    percentage: '90%',
    image: '/images/logos/css-logo.png',
  },
  {
    id: 3,
    name: 'JavaScript',
    percentage: '85%',
    image: '/images/logos/js-logo.png',
  },
  {
    id: 4,
    name: 'Tailwind',
    percentage: '95%',
    image: '/images/logos/tailwind-logo.png',
  },
  {
    id: 5,
    name: 'ReactJS',
    percentage: '85%',
    image: '/images/logos/react-logo.png',
  },
  {
    id: 6,
    name: 'NextJS',
    percentage: '80%',
    image: '/images/logos/next-logo.png',
  },
  {
    id: 7,
    name: 'Laravel',
    percentage: '70%',
    image: '/images/logos/laravel-logo.png',
  },
  {
    id: 8,
    name: 'Django',
    percentage: '60%',
    image: '/images/logos/django-logo.png',
  },
  {
    id: 9,
    name: 'Python',
    percentage: '70%',
    image: '/images/logos/python-logo.png',
  },
  {
    id: 10,
    name: 'PHP',
    percentage: '60%',
    image: '/images/logos/php-logo.png',
  },
  {
    id: 11,
    name: 'Java',
    percentage: '60%',
    image: '/images/logos/java-logo.png',
  },
  {
    id: 12,
    name: 'C++',
    percentage: '40%',
    image: '/images/logos/cpp-logo.png',
  },
  {
    id: 13,
    name: 'R',
    percentage: '45%',
    image: '/images/logos/r-logo.png',
  },
  {
    id: 14,
    name: 'SQL',
    percentage: '85%',
    image: '/images/logos/sql-logo.png',
  },
];
