export const projectsData = [
  {
    id: 8,
    title: 'Next13-Template',
    desc: 'Next13-Template App with TypeScript, TailwindCSS, tanstack, schadcnui, husky, and more!',
    liveUrl: 'https://template-next13.vercel.app/',
    gitUrl: 'https://github.com/nathanaelpganata/next13-template',
    img: '/images/projects/next13template-preview.png',
    date: '20 Aug 2023',
    stacks: [
      { id: 1, name: 'NextJS' },
      { id: 2, name: 'Typescript' },
      { id: 3, name: 'TailwindCSS' },
      { id: 4, name: 'tanstack' },
      { id: 5, name: 'schadcnui' },
    ],
  },
  {
    id: 8,
    title: 'Kyoyu [frontend]',
    desc: 'Kyoyu is a web application for sharing your day. This is the frontend repository built using seamless authentication and authorization server-side cookie.',
    gitUrl: 'https://github.com/nathanaelpganata/kyoyu-frontend',
    img: '/images/projects/kyoyu-fe-preview.png',
    date: '15 Aug 2023',
    stacks: [
      { id: 1, name: 'NextJS' },
      { id: 2, name: 'Typescript' },
      { id: 3, name: 'TailwindCSS' },
      { id: 4, name: 'tanstack' },
    ],
  },
  {
    id: 10,
    title: 'Kyoyu [backend]',
    desc: 'Kyoyu is a web application for sharing your day. This is the backend repository built using a minimalistic approach on simple CRUD and secure authentication & authorization.',
    gitUrl: 'https://github.com/nathanaelpganata/kyoyu-backend',
    img: '/images/projects/kyoyu-be-preview.png',
    date: '15 Aug 2023',
    stacks: [
      { id: 1, name: 'Go' },
      { id: 2, name: 'Gin' },
      { id: 3, name: 'Gorm' },
      { id: 4, name: 'Postgres' },
    ],
  },
  {
    id: 10,
    title: 'Poste Full Stack',
    desc: ' NextJS 13 full stack application with next-auth, react-hook-form, prisma, and mysql. Complete with CRUD, authentication, and authorization.',
    gitUrl: 'https://github.com/nathanaelpganata/poste-full-stack',
    img: '/images/projects/poste-fullstack-preview.png',
    date: '22 Jul 2023',
    stacks: [
      { id: 1, name: 'NextJS' },
      { id: 2, name: 'Typescript' },
      { id: 3, name: 'TailwindCSS' },
      { id: 4, name: 'Prisma' },
      { id: 5, name: 'Next-Auth' },
    ],
  },
  {
    id: 1,
    title: 'AniQ',
    desc: 'An anime index website to search for anime and view relevant information in one-page application. Built using ReactJS, TailwindCSS, and Tanstack Query.',
    liveUrl: 'https://nathanaelpganata.github.io/AniQ/',
    gitUrl: 'https://github.com/nathanaelpganata/AniQ',
    img: '/images/projects/aniq-preview.png',
    date: '08 Jul 2022',
    stacks: [
      { id: 1, name: 'ReactJS' },
      { id: 2, name: 'TailwindCSS' },
      { id: 2, name: 'Tanstack' },
    ],
  },
  {
    id: 2,
    title: 'UX Portfolio',
    desc: 'A personal user experience design portfolio website built as a capstone project from Coursera UX Specialization provided by Google.',
    liveUrl: 'https://ux.nathanpg.vercel.app/',
    gitUrl: 'https://github.com/nathanaelpganata/ux-portfolio',
    img: '/images/projects/uxportfolio-preview.png',
    date: '02 May 2023',
    stacks: [
      { id: 3, name: 'NextJS' },
      { id: 2, name: 'TypeScript' },
      { id: 1, name: 'TailwindCSS' },
    ],
  },
  {
    id: 3,
    title: 'Learn ThreeJS',
    desc: 'A ThreeJS demonstration and learning website',
    liveUrl: 'https://learn-threejs.nathanpg.vercel.app',
    gitUrl: 'https://github.com/nathanaelpganata/learn-threejs',
    img: '/images/projects/learnthreejs-preview.png',
    date: '14 May 2022',
    stacks: [
      { id: 3, name: 'NextJS' },
      { id: 2, name: 'TypeScript' },
      { id: 1, name: 'TailwindCSS' },
    ],
  },
  {
    id: 4,
    title: 'ITS Expo 2023',
    desc: 'Website for ITS Expo 2023',
    liveUrl: 'https://expo-its.com',
    img: '/images/projects/itsexpo23-preview.png',
    date: '10 January 2023',
    stacks: [
      { id: 1, name: 'NextJS' },
      { id: 2, name: 'TypeScript' },
      { id: 2, name: 'TailwindCSS' },
      { id: 3, name: 'Laravel' },
    ],
  },
  {
    id: 5,
    title: 'Ini Lho ITS 2023',
    desc: 'Website for Ini Lho ITS 2023 event',
    liveUrl: 'https://inilho.its.ac.id',
    img: '/images/projects/ilits23-preview.png',
    date: '24 December 2022',
    stacks: [
      { id: 1, name: 'NextJS' },
      { id: 2, name: 'TypeScript' },
      { id: 2, name: 'TailwindCSS' },
      { id: 3, name: 'NestJS' },
    ],
  },
  {
    id: 6,
    title: 'Information System Expo 2022',
    desc: 'A website for ISE 2022 event',
    liveUrl: 'https://ise-its.com',
    img: '/images/projects/ise22-preview.png',
    date: '15 June 2022',
    stacks: [
      { id: 1, name: 'AlpineJS' },
      { id: 2, name: 'Laravel' },
      { id: 3, name: 'TailwindCSS' },
    ],
  },
];
