export const projectsData = [
  {
    id: 1,
    title: 'AniQ',
    desc: 'An anime index website made with JikanAPI',
    url: 'https://nathanaelpganata.github.io/AniQ/',
    img: '/images/projects/aniq-preview.png',
    date: '08 July 2022',
    stacks: [
      { id: 1, name: 'ReactJS' },
      { id: 2, name: 'TailwindCSS' },
    ],
  },
  {
    id: 2,
    title: 'UX Portfolio',
    desc: 'A personal user experience design portfolio website',
    url: 'https://ux.nathanpg.vercel.app/',
    img: '/images/projects/uxportfolio-preview.png',
    date: '02 May 2023',
    stacks: [
      { id: 3, name: 'NextJS' },
      { id: 2, name: 'TypeScript' },
      { id: 1, name: 'TailwindCSS' },
    ],
  },
  {
    id: 3,
    title: 'Learn ThreeJS',
    desc: 'A ThreeJS demonstration and learning website',
    url: 'https://learn-threejs.nathanpg.vercel.app',
    img: '/images/projects/learnthreejs-preview.png',
    date: '14 May 2022',
    stacks: [
      { id: 3, name: 'NextJS' },
      { id: 2, name: 'TypeScript' },
      { id: 1, name: 'TailwindCSS' },
    ],
  },
  {
    id: 4,
    title: 'ITS Expo 2023',
    desc: 'Website for ITS Expo 2023',
    url: 'https://expo-its.com',
    img: '/images/projects/itsexpo23-preview.png',
    date: '10 January 2023',
    stacks: [
      { id: 1, name: 'NextJS' },
      { id: 2, name: 'TypeScript' },
      { id: 2, name: 'TailwindCSS' },
      { id: 3, name: 'Laravel' },
    ],
  },
  {
    id: 5,
    title: 'Ini Lho ITS 2023',
    desc: 'Website for Ini Lho ITS 2023 event',
    url: 'https://inilho.its.ac.id',
    img: '/images/projects/ilits23-preview.png',
    date: '24 December 2022',
    stacks: [
      { id: 1, name: 'NextJS' },
      { id: 2, name: 'TypeScript' },
      { id: 2, name: 'TailwindCSS' },
      { id: 3, name: 'NestJS' },
    ],
  },
  {
    id: 6,
    title: 'Information System Expo 2022',
    desc: 'A website for ISE 2022 event',
    url: 'https://ise-its.com',
    img: '/images/projects/ise22-preview.png',
    date: '15 June 2022',
    stacks: [
      { id: 1, name: 'AlpineJS' },
      { id: 2, name: 'Laravel' },
      { id: 3, name: 'TailwindCSS' },
    ],
  },
  {
    id: 7,
    title: 'Github',
    desc: 'Visit my github profile for more projects',
    url: 'https://github.com/nathanaelpganata',
    img: '/images/projects/github-preview.png',
    date: '',
  },
];
