export const projectsData = [
  {
    id: 1,
    title: 'AniQ',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem laborum quo saepe nam excepturi, ipsa expedita eveniet quasi ea possimus placeat iste hic magni maiores et facere. Inventore, suscipit! Minus.',
    url: 'www.haha',
    img: '/images/profile-picture.jpg',
    date: '02 Jan 2021',
    stacks: [
      { id: 1, name: 'ReactJS' },
      { id: 1, name: 'TailwindCSS' },
      { id: 1, name: 'HTML' },
    ],
  },
  {
    id: 1,
    title: 'AniQ',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem laborum quo saepe nam excepturi, ipsa expedita eveniet quasi ea possimus placeat iste hic magni maiores et facere. Inventore, suscipit! Minus.',
    url: 'www.haha',
    img: '/images/profile-picture.jpg',
    date: '02 Jan 2022',
    stacks: [
      { id: 1, name: 'ReactJS' },
      { id: 1, name: 'TailwindCSS' },
      { id: 1, name: 'HTML' },
    ],
  },
  {
    id: 1,
    title: 'AniQ',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem laborum quo saepe nam excepturi, ipsa expedita eveniet quasi ea possimus placeat iste hic magni maiores et facere. Inventore, suscipit! Minus.',
    url: 'www.haha',
    img: '/images/profile-picture.jpg',
    date: '02 Jan 2023',
    stacks: [
      { id: 1, name: 'ReactJS' },
      { id: 1, name: 'TailwindCSS' },
      { id: 1, name: 'HTML' },
    ],
  },
  {
    id: 1,
    title: 'AniQ',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem laborum quo saepe nam excepturi, ipsa expedita eveniet quasi ea possimus placeat iste hic magni maiores et facere. Inventore, suscipit! Minus.',
    url: 'www.haha',
    img: '/images/profile-picture.jpg',
    date: '02 Jan 2020',
    stacks: [
      { id: 1, name: 'ReactJS' },
      { id: 1, name: 'TailwindCSS' },
      { id: 1, name: 'HTML' },
    ],
  },
  {
    id: 1,
    title: 'AniQ',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem laborum quo saepe nam excepturi, ipsa expedita eveniet quasi ea possimus placeat iste hic magni maiores et facere. Inventore, suscipit! Minus.',
    url: 'www.haha',
    img: '/images/profile-picture.jpg',
    date: '02 Jan 2020',
    stacks: [
      { id: 1, name: 'ReactJS' },
      { id: 1, name: 'TailwindCSS' },
      { id: 1, name: 'HTML' },
    ],
  },
  {
    id: 1,
    title: 'AniQ',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem laborum quo saepe nam excepturi, ipsa expedita eveniet quasi ea possimus placeat iste hic magni maiores et facere. Inventore, suscipit! Minus.',
    url: 'www.haha',
    img: '/images/profile-picture.jpg',
    date: '02 Jan 2020',
    stacks: [
      { id: 1, name: 'ReactJS' },
      { id: 1, name: 'TailwindCSS' },
      { id: 1, name: 'HTML' },
    ],
  },
];
